name: acronym
version: 1.3.0.5

dependencies:
  - base

library:
  exposed-modules: Acronym
  source-dirs: src
  dependencies: split

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec
