name: robot-simulator
version: 2.2.0.5

dependencies:
  - base

library:
  exposed-modules: Robot
  source-dirs: src
  dependencies: lens

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - robot-simulator
      - hspec
